### ISSUE TITLE
How to handle large number of stickers ?

### ISSUE THREAD

**Issue by romainricard** [romainricard/signalstickers#47]
As we add stickers to this site, the flat file containing packs ID, key and tags will probably show its limits, as a user has to load the whole list to be able to search and sort (packs title are fetched from signal.art). 

One way to handle this problem is to fetch info for packs at build time, as @sticker201 proposed.

**Comment by darkobits** [comment]
Do we feel that this was satisfactorily addressed by https://github.com/romainricard/signalstickers/pull/49?

**Comment by sticker201** [comment]
yes, for the foreseeable future until we 10x the pack count again i think this would be satisfactory
