### ISSUE TITLE
No image in Safari

### ISSUE THREAD

**Issue by romainricard** [romainricard/signalstickers#6]
Safari does not support webp images, returned by the Signal CDN.

**Comment by romainricard** [comment]
This should makes the trick https://github.com/chase-moskal/webp-hero/issues/27

**Comment by BeTmAsTeR** [comment]
Use something like cloudinary as temporary fix?
https://support.cloudinary.com/hc/en-us/articles/203125741-Can-I-upload-using-DATA-URI-BASE64-

**Comment by romainricard** [comment]
This could be a temporary fix, but I'm worried about where the data is going. I'm working on a small piece of code that could do the trick

**Comment by muellermartin** [comment]
I've created PR #42 which somewhat fixes this issue though there are some odd bugs which I can't figure out (the canvas for the WebP images sometimes stays emtpy without any error or notice).

**Comment by romainricard** [comment]
Fixed by @muellermartin in https://github.com/romainricard/signalstickers/pull/42 . Thank you for your contribution!
On a side note, I wasn't able to reproduce the bug.
