### ISSUE TITLE
Sort by date added

### ISSUE THREAD

**Issue by maxhawkins** [romainricard/signalstickers#65]
It would be nice to allow sorting by date added.

I keep coming back to the site to see if there are new stickers but I have to search through the entire list.

**Comment by darkobits** [comment]
Adding this kind of field, given the architecture of this product, is not trivial. It would likely either have to be manual (and therefore prone to error) or some additional tooling would have to be built to cleverly inject a timestamp into each object in `stickers.yml` at some point in the build job.

Happy to hear from others if they have thoughts on this, but I think we have to be very mindful of the cost/benefit of a feature like this with our current setup.

**Comment by sticker201** [comment]
> It would likely either have to be manual (and therefore prone to error) or some additional tooling would have to be built to cleverly inject a timestamp into each object in `stickers.yml` at some point in the build job.

We could maybe assume the stickers in stickers.yml are in order of date added? Since new ones get added at the end. Seems like it wouldn't be _too_ costly.
