### ISSUE TITLE
Changes to Q&A section in README

### ISSUE THREAD

**Issue by ondondil** [romainricard/signalstickers#7]
[Turns out](https://community.signalusers.org/t/sticker-pack-collection-thread-makeprivacystick/10650/155) that 16px gap is just something nice to have but totally unnecessary.
Quoting one of Signal employees: 
> I have seen the script that adds another 16px when importing from elsewhere, I really think that is unnecessary, most sticker images from elsewhere would already have a sufficient gap.

Some sticker packs are not prepared for dark themes so they need changes like [this](https://gist.github.com/ondondil/4b8564b404696b3255253b467b413de9#gistcomment-3118471). But some others already do have a white outline and they don't need that treatment, so it depends on individual sticker pack.

IMO, given all that, link to [this gist](https://gist.github.com/ondondil/4b8564b404696b3255253b467b413de9) should be removed or [this part](https://gist.github.com/ondondil/4b8564b404696b3255253b467b413de9) of Q&A rewritten completely to guide people through the whole process of downloading and preparing images for upload.
For example, if a Telegram sticker pack already has proper padding and white outline, it doesn't need any kind of conversion. You'd just download it from a website and upload as Signal sticker pack without any changes done to the images.

**Comment by romainricard** [comment]
We've update the README multiple time, I think now it helps correctly the user to create sticker pack. @ondondil do no hesitate to open a PR to modify the README (at least the EN, I'll modify the DE and FR) if you feel like it's still not enough! Closing this one for now.
