### ISSUE TITLE
Pusheen 3.0 sticker pack is broken

### ISSUE THREAD

**Issue by j-mikhail** [romainricard/signalstickers#75]
Receive an "error opening sticker pack" when attempting to install this pack: https://signalstickers.com/pack/0ca57dfbddb36e108719926b347b8cca 

No issues with other packs.

**Comment by romainricard** [comment]
That's weird! I can't reproduce either on mobile or desktop.
We might need some more info: on which platform, which browser, and a screenshot if you can.
Thank you!

**Comment by j-mikhail** [comment]
Interesting! I'm running Vivaldi 64-bit v2.9.1705.41 on Windows 10 Pro 64-bit (v1903, build 18362.476) and Signal v1.29.6.

So what happens is I click the link to open Signal, then the typical window appears very briefly where it begins loading the sticker images sequentially, with the install button on the bottom  It happens very quickly, but once it gets to the 5th or 6th image, the window switches to this instead: 

![image](https://user-images.githubusercontent.com/3420913/72805119-25dbc000-3c20-11ea-9cf2-e9674fd0e065.png)

I have not been able to find any Signal logs that I can refer to. If Signal does keep logs, can you point me to where they are stored?

**Comment by romainricard** [comment]
So the problem is on the Signal side. Just to confirm, does the bug appends when you try directly from the `signal.art` link? https://signal.art/addstickers/#pack_id=0ca57dfbddb36e108719926b347b8cca&pack_key=64d1be8aaa37230e5777613b81517c25a8b6a2d145180f28129b750bedea0218

If the problem is on their side, we can't do much. You can open an Issue on the [Signal Desktop repo](https://github.com/signalapp/Signal-Desktop), and [give them your log file](https://support.signal.org/hc/en-us/articles/360007318591-Debug-Logs-and-Crash-Reports).

**Comment by j-mikhail** [comment]
Yes, the bug still appears with your direct link.

I can confirm that it does work on mobile. But, I note that the fourth image is blank even on mobile. Perhaps this is the offending image?

![image](https://user-images.githubusercontent.com/3420913/72805687-77387f00-3c21-11ea-9fa7-cb43dfd74431.png)

I will bring it up with the Signal team, thanks.

**Comment by romainricard** [comment]
Okay, I managed to reproduce. There is indeed a bug with this pack.
You might still want to open an Issue on [Signal-Desktop](https://github.com/signalapp/Signal-Desktop), as such an error is weird. We'll see if we remove this pack for now. Thanks again! 

```
INFO  2020-01-21T12:40:33.523Z Remove all notifications
INFO  2020-01-21T12:40:33.600Z Opening sticker pack from sgnl protocol link
INFO  2020-01-21T12:40:33.612Z GET https://cdn.signal.org/stickers/[REDACTED]cca/manifest.proto
INFO  2020-01-21T12:40:33.653Z GET https://cdn.signal.org/stickers/[REDACTED]cca/manifest.proto 200 Success
INFO  2020-01-21T12:40:33.665Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/0
INFO  2020-01-21T12:40:33.712Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/0 200 Success
INFO  2020-01-21T12:40:33.737Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/1
INFO  2020-01-21T12:40:33.738Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/2
INFO  2020-01-21T12:40:33.739Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/3
INFO  2020-01-21T12:40:33.771Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/1 200 Success
INFO  2020-01-21T12:40:33.780Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/4
INFO  2020-01-21T12:40:33.813Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/2 200 Success
INFO  2020-01-21T12:40:33.822Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/5
INFO  2020-01-21T12:40:34.154Z GET https://cdn.signal.org/stickers/[REDACTED]cca/full/3 403 Error
ERROR 2020-01-21T12:40:34.180Z Ephemeral download error for sticker pack [REDACTED]cca: HTTPError: promiseAjax: error response; code: 403
    at HTTPError ([REDACTED]/app.asar/js/modules/web_api.js:380:13)
    at [REDACTED]/app.asar/js/modules/web_api.js:336:13
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
Original stack:
Error
    at _outerAjax ([REDACTED]/app.asar/js/modules/web_api.js:374:19)
    at Object.getSticker ([REDACTED]/app.asar/js/modules/web_api.js:858:14)
    at MessageSender.getSticker (file://[REDACTED]/app.asar/js/libtextsecure.js:40768:24)
    at downloadSticker ([REDACTED]/app.asar/js/modules/stickers.js:251:49)
    at downloadStickerJob ([REDACTED]/app.asar/js/modules/stickers.js:372:33)
    at [REDACTED]/app.asar/node_modules/p-map/index.js:47:21
```
